In [133]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import matplotlib as mpl
from sklearn.model_selection import train_test_split

In [4]:
#正常显示中文
mpl.rcParams['font.sans-serif']=[u'SimHei']
mpl.rcParams['axes.unicode_minus'] = False

In [5]:
#用于抑制第三方警告
warnings.filterwarnings("ignore")

In [109]:
pd.options.display.max_rows = 10   #最大显示10行
data = pd.read_csv(r"C:\Users\hu\Desktop\datasets\data.csv",encoding = "gbk")  #读取数据  
data

,Unnamed: 0,custid,trade_no,bank_card_no,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,5,2791858,20180507115231274000000023057383,卡号1,0.01,0.99,0,0.90,0.55,0.313,...,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,10,534047,20180507121002192000000023073000,卡号1,0.02,0.94,2000,1.28,1.00,0.458,...,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,12,2849787,20180507125159718000000023114911,卡号1,0.04,0.96,0,1.00,1.00,0.114,...,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,13,1809708,20180507121358683000000388283484,卡号1,0.00,0.96,2000,0.13,0.57,0.777,...,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,14,2499829,20180507115448545000000388205844,卡号1,0.01,0.99,0,0.46,1.00,0.175,...,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4749,11978,3269862,20180507120519228000000388247328,卡号1,0.05,0.68,1000,0.87,0.94,0.150,...,0.0,0.0,49200.0,78.0,1.0,1.0,49200.0,49200.0,44.0,58.0
4750,11986,270952,20180507114937914000000388192877,卡号1,0.01,0.99,400,0.93,0.98,0.605,...,5000.0,1952.0,10100.0,78.0,7.0,8.0,19200.0,7500.0,17.0,55.0
4751,11988,2425913,20180507121340509000000388278785,卡号1,0.00,1.00,3000,0.54,0.64,0.313,...,3300.0,1540.0,7600.0,79.0,8.0,8.0,21000.0,7250.0,18.0,55.0
4752,11991,471395,20180504161827128000000381357758,卡号1,0.05,0.95,0,4.79,1.00,0.458,...,1900.0,1216.0,7100.0,79.0,8.0,11.0,12000.0,3950.0,55.0,16.0
4753,11992,1881943,20180507124243041000000388391027,卡号1,0.01,0.99,1300,21.35,1.00,0.372,...,4000.0,2180.0,4500.0,74.0,5.0,5.0,7800.0,4360.0,20.0,54.0

In [110]:
data.info()  #显示数据的详细信息，有没有空行等。

print()
print("Number of datasets: " + str(data.shape[0])+" rows")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4754 entries, 0 to 4753
Data columns (total 90 columns):
Unnamed: 0                                    4754 non-null int64
custid                                        4754 non-null int64
trade_no                                      4754 non-null object
bank_card_no                                  4754 non-null object
low_volume_percent                            4752 non-null float64
middle_volume_percent                         4752 non-null float64
take_amount_in_later_12_month_highest         4754 non-null int64
trans_amount_increase_rate_lately             4751 non-null float64
trans_activity_month                          4752 non-null float64
trans_activity_day                            4752 non-null float64
transd_mcc                                    4752 non-null float64
trans_days_interval_filter                    4746 non-null float64
trans_days_interval                           4752 non-null float64
regional_mobility                             4752 non-null float64
student_feature                               1756 non-null float64
repayment_capability                          4754 non-null int64
is_high_user                                  4754 non-null int64
number_of_trans_from_2011                     4752 non-null float64
first_transaction_time                        4752 non-null float64
historical_trans_amount                       4754 non-null int64
historical_trans_day                          4752 non-null float64
rank_trad_1_month                             4752 non-null float64
trans_amount_3_month                          4754 non-null int64
avg_consume_less_12_valid_month               4752 non-null float64
abs                                           4754 non-null int64
top_trans_count_last_1_month                  4752 non-null float64
avg_price_last_12_month                       4754 non-null int64
avg_price_top_last_12_valid_month             4650 non-null float64
reg_preference_for_trad                       4752 non-null object
trans_top_time_last_1_month                   4746 non-null float64
trans_top_time_last_6_month                   4746 non-null float64
consume_top_time_last_1_month                 4746 non-null float64
consume_top_time_last_6_month                 4746 non-null float64
cross_consume_count_last_1_month              4328 non-null float64
trans_fail_top_count_enum_last_1_month        4738 non-null float64
trans_fail_top_count_enum_last_6_month        4738 non-null float64
trans_fail_top_count_enum_last_12_month       4738 non-null float64
consume_mini_time_last_1_month                4728 non-null float64
max_cumulative_consume_later_1_month          4754 non-null int64
max_consume_count_later_6_month               4746 non-null float64
railway_consume_count_last_12_month           4742 non-null float64
pawns_auctions_trusts_consume_last_1_month    4754 non-null int64
pawns_auctions_trusts_consume_last_6_month    4754 non-null int64
jewelry_consume_count_last_6_month            4742 non-null float64
status                                        4754 non-null int64
source                                        4754 non-null object
first_transaction_day                         4752 non-null float64
trans_day_last_12_month                       4752 non-null float64
id_name                                       4478 non-null object
apply_score                                   4450 non-null float64
apply_credibility                             4450 non-null float64
query_org_count                               4450 non-null float64
query_finance_count                           4450 non-null float64
query_cash_count                              4450 non-null float64
query_sum_count                               4450 non-null float64
latest_query_time                             4450 non-null object
latest_one_month_apply                        4450 non-null float64
latest_three_month_apply                      4450 non-null float64
latest_six_month_apply                        4450 non-null float64
loans_score                                   4457 non-null float64
loans_credibility_behavior                    4457 non-null float64
loans_count                                   4457 non-null float64
loans_settle_count                            4457 non-null float64
loans_overdue_count                           4457 non-null float64
loans_org_count_behavior                      4457 non-null float64
consfin_org_count_behavior                    4457 non-null float64
loans_cash_count                              4457 non-null float64
latest_one_month_loan                         4457 non-null float64
latest_three_month_loan                       4457 non-null float64
latest_six_month_loan                         4457 non-null float64
history_suc_fee                               4457 non-null float64
history_fail_fee                              4457 non-null float64
latest_one_month_suc                          4457 non-null float64
latest_one_month_fail                         4457 non-null float64
loans_long_time                               4457 non-null float64
loans_latest_time                             4457 non-null object
loans_credit_limit                            4457 non-null float64
loans_credibility_limit                       4457 non-null float64
loans_org_count_current                       4457 non-null float64
loans_product_count                           4457 non-null float64
loans_max_limit                               4457 non-null float64
loans_avg_limit                               4457 non-null float64
consfin_credit_limit                          4457 non-null float64
consfin_credibility                           4457 non-null float64
consfin_org_count_current                     4457 non-null float64
consfin_product_count                         4457 non-null float64
consfin_max_limit                             4457 non-null float64
consfin_avg_limit                             4457 non-null float64
latest_query_day                              4450 non-null float64
loans_latest_day                              4457 non-null float64
dtypes: float64(70), int64(13), object(7)
memory usage: 3.3+ MB

Number of datasets: 4754 rows

In [111]:
data.columns = [str.replace("-","_") for str in data.columns]

In [112]:
for i,name in enumerate(data.columns):
    name_sum = data[name].value_counts().shape[0]
    print("{:2}、{:40}     The number of types of features is: {}".format(i+1,name,name_sum))

 1、Unnamed: 0                                   The number of types of features is: 4754
 2、custid                                       The number of types of features is: 4754
 3、trade_no                                     The number of types of features is: 4754
 4、bank_card_no                                 The number of types of features is: 1
 5、low_volume_percent                           The number of types of features is: 40
 6、middle_volume_percent                        The number of types of features is: 90
 7、take_amount_in_later_12_month_highest        The number of types of features is: 166
 8、trans_amount_increase_rate_lately            The number of types of features is: 782
 9、trans_activity_month                         The number of types of features is: 84
10、trans_activity_day                           The number of types of features is: 512
11、transd_mcc                                   The number of types of features is: 41
12、trans_days_interval_filter                   The number of types of features is: 147
13、trans_days_interval                          The number of types of features is: 114
14、regional_mobility                            The number of types of features is: 5
15、student_feature                              The number of types of features is: 2
16、repayment_capability                         The number of types of features is: 2390
17、is_high_user                                 The number of types of features is: 2
18、number_of_trans_from_2011                    The number of types of features is: 70
19、first_transaction_time                       The number of types of features is: 1693
20、historical_trans_amount                      The number of types of features is: 4524
21、historical_trans_day                         The number of types of features is: 476
22、rank_trad_1_month                            The number of types of features is: 20
23、trans_amount_3_month                         The number of types of features is: 3524
24、avg_consume_less_12_valid_month              The number of types of features is: 12
25、abs                                          The number of types of features is: 1697
26、top_trans_count_last_1_month                 The number of types of features is: 8
27、avg_price_last_12_month                      The number of types of features is: 330
28、avg_price_top_last_12_valid_month            The number of types of features is: 20
29、reg_preference_for_trad                      The number of types of features is: 5
30、trans_top_time_last_1_month                  The number of types of features is: 28
31、trans_top_time_last_6_month                  The number of types of features is: 97
32、consume_top_time_last_1_month                The number of types of features is: 28
33、consume_top_time_last_6_month                The number of types of features is: 94
34、cross_consume_count_last_1_month             The number of types of features is: 19
35、trans_fail_top_count_enum_last_1_month       The number of types of features is: 15
36、trans_fail_top_count_enum_last_6_month       The number of types of features is: 25
37、trans_fail_top_count_enum_last_12_month      The number of types of features is: 26
38、consume_mini_time_last_1_month               The number of types of features is: 1971
39、max_cumulative_consume_later_1_month         The number of types of features is: 863
40、max_consume_count_later_6_month              The number of types of features is: 29
41、railway_consume_count_last_12_month          The number of types of features is: 6
42、pawns_auctions_trusts_consume_last_1_month     The number of types of features is: 572
43、pawns_auctions_trusts_consume_last_6_month     The number of types of features is: 2730
44、jewelry_consume_count_last_6_month           The number of types of features is: 7
45、status                                       The number of types of features is: 2
46、source                                       The number of types of features is: 1
47、first_transaction_day                        The number of types of features is: 1693
48、trans_day_last_12_month                      The number of types of features is: 132
49、id_name                                      The number of types of features is: 4309
50、apply_score                                  The number of types of features is: 205
51、apply_credibility                            The number of types of features is: 41
52、query_org_count                              The number of types of features is: 46
53、query_finance_count                          The number of types of features is: 25
54、query_cash_count                             The number of types of features is: 17
55、query_sum_count                              The number of types of features is: 74
56、latest_query_time                            The number of types of features is: 207
57、latest_one_month_apply                       The number of types of features is: 36
58、latest_three_month_apply                     The number of types of features is: 56
59、latest_six_month_apply                       The number of types of features is: 65
60、loans_score                                  The number of types of features is: 247
61、loans_credibility_behavior                   The number of types of features is: 25
62、loans_count                                  The number of types of features is: 134
63、loans_settle_count                           The number of types of features is: 123
64、loans_overdue_count                          The number of types of features is: 26
65、loans_org_count_behavior                     The number of types of features is: 41
66、consfin_org_count_behavior                   The number of types of features is: 19
67、loans_cash_count                             The number of types of features is: 32
68、latest_one_month_loan                        The number of types of features is: 14
69、latest_three_month_loan                      The number of types of features is: 31
70、latest_six_month_loan                        The number of types of features is: 67
71、history_suc_fee                              The number of types of features is: 171
72、history_fail_fee                             The number of types of features is: 151
73、latest_one_month_suc                         The number of types of features is: 19
74、latest_one_month_fail                        The number of types of features is: 41
75、loans_long_time                              The number of types of features is: 202
76、loans_latest_time                            The number of types of features is: 232
77、loans_credit_limit                           The number of types of features is: 54
78、loans_credibility_limit                      The number of types of features is: 33
79、loans_org_count_current                      The number of types of features is: 32
80、loans_product_count                          The number of types of features is: 32
81、loans_max_limit                              The number of types of features is: 91
82、loans_avg_limit                              The number of types of features is: 961
83、consfin_credit_limit                         The number of types of features is: 327
84、consfin_credibility                          The number of types of features is: 24
85、consfin_org_count_current                    The number of types of features is: 19
86、consfin_product_count                        The number of types of features is: 20
87、consfin_max_limit                            The number of types of features is: 175
88、consfin_avg_limit                            The number of types of features is: 1677
89、latest_query_day                             The number of types of features is: 210
90、loans_latest_day                             The number of types of features is: 235

In [113]:
data.describe()

,Unnamed: 0,custid,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
count,4754.000000,4.754000e+03,4752.000000,4752.000000,4754.000000,4751.000000,4752.000000,4752.000000,4752.000000,4746.000000,...,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4457.000000,4450.000000,4457.000000
mean,6008.414178,1.690993e+06,0.021806,0.901294,1940.197728,14.160674,0.804411,0.365425,17.502946,29.029920,...,3390.038142,1820.357864,9187.009199,76.042630,4.732331,5.227507,16153.690823,8007.696881,24.112809,55.181512
std,3452.071428,1.034235e+06,0.041527,0.144856,3923.971494,694.180473,0.196920,0.170196,4.475616,22.722432,...,1474.206546,583.418291,7371.257043,14.536819,2.974596,3.409292,14301.037628,5679.418585,37.725724,53.486408
min,5.000000,1.140000e+02,0.000000,0.000000,0.000000,0.000000,0.120000,0.033000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-2.000000,-2.000000
25%,3106.000000,7.593358e+05,0.010000,0.880000,0.000000,0.615000,0.670000,0.233000,15.000000,16.000000,...,2300.000000,1535.000000,4800.000000,77.000000,2.000000,3.000000,7800.000000,4737.000000,5.000000,10.000000
50%,6006.500000,1.634942e+06,0.010000,0.960000,500.000000,0.970000,0.860000,0.350000,17.000000,23.000000,...,3100.000000,1810.000000,7700.000000,79.000000,4.000000,5.000000,13800.000000,7050.000000,14.000000,36.000000
75%,8999.000000,2.597905e+06,0.020000,0.990000,2000.000000,1.600000,1.000000,0.480000,20.000000,32.000000,...,4300.000000,2100.000000,11700.000000,80.000000,7.000000,7.000000,20400.000000,10000.000000,24.000000,91.000000
max,11992.000000,4.004694e+06,1.000000,1.000000,68000.000000,47596.740000,1.000000,0.941000,42.000000,285.000000,...,10000.000000,6900.000000,87100.000000,87.000000,18.000000,20.000000,266400.000000,82800.000000,360.000000,323.000000

In [114]:
for columns in data.columns:
    data.loc[data[columns] == "NA",columns] = np.nan

In [115]:
Irrelevant_features = ['Unnamed: 0', 'custid', 'trade_no', 'bank_card_no', 'source', 'id_name', 'latest_query_time','loans_latest_time']
data = data.drop(Irrelevant_features,axis = 1)

In [116]:
data["student_feature"]

0       NaN
1       1.0
2       NaN
3       NaN
4       NaN
       ...
4749    1.0
4750    1.0
4751    NaN
4752    NaN
4753    1.0
Name: student_feature, Length: 4754, dtype: float64

In [117]:
data.head()

,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,trans_days_interval,regional_mobility,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,0.01,0.99,0.0,0.90,0.55,0.313,17.0,27.0,26.0,3.0,...,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,0.02,0.94,2000.0,1.28,1.00,0.458,19.0,30.0,14.0,4.0,...,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,0.04,0.96,0.0,1.00,1.00,0.114,13.0,68.0,22.0,1.0,...,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,0.00,0.96,2000.0,0.13,0.57,0.777,22.0,14.0,6.0,3.0,...,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,0.01,0.99,0.0,0.46,1.00,0.175,13.0,66.0,42.0,1.0,...,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0

In [118]:
pd.options.display.max_rows = 82   #显示所有行数
data.dtypes

low_volume_percent                            float64
middle_volume_percent                         float64
take_amount_in_later_12_month_highest         float64
trans_amount_increase_rate_lately             float64
trans_activity_month                          float64
trans_activity_day                            float64
transd_mcc                                    float64
trans_days_interval_filter                    float64
trans_days_interval                           float64
regional_mobility                             float64
student_feature                               float64
repayment_capability                          float64
is_high_user                                  float64
number_of_trans_from_2011                     float64
first_transaction_time                        float64
historical_trans_amount                       float64
historical_trans_day                          float64
rank_trad_1_month                             float64
trans_amount_3_month                          float64
avg_consume_less_12_valid_month               float64
abs                                           float64
top_trans_count_last_1_month                  float64
avg_price_last_12_month                       float64
avg_price_top_last_12_valid_month             float64
reg_preference_for_trad                        object
trans_top_time_last_1_month                   float64
trans_top_time_last_6_month                   float64
consume_top_time_last_1_month                 float64
consume_top_time_last_6_month                 float64
cross_consume_count_last_1_month              float64
trans_fail_top_count_enum_last_1_month        float64
trans_fail_top_count_enum_last_6_month        float64
trans_fail_top_count_enum_last_12_month       float64
consume_mini_time_last_1_month                float64
max_cumulative_consume_later_1_month          float64
max_consume_count_later_6_month               float64
railway_consume_count_last_12_month           float64
pawns_auctions_trusts_consume_last_1_month    float64
pawns_auctions_trusts_consume_last_6_month    float64
jewelry_consume_count_last_6_month            float64
status                                        float64
first_transaction_day                         float64
trans_day_last_12_month                       float64
apply_score                                   float64
apply_credibility                             float64
query_org_count                               float64
query_finance_count                           float64
query_cash_count                              float64
query_sum_count                               float64
latest_one_month_apply                        float64
latest_three_month_apply                      float64
latest_six_month_apply                        float64
loans_score                                   float64
loans_credibility_behavior                    float64
loans_count                                   float64
loans_settle_count                            float64
loans_overdue_count                           float64
loans_org_count_behavior                      float64
consfin_org_count_behavior                    float64
loans_cash_count                              float64
latest_one_month_loan                         float64
latest_three_month_loan                       float64
latest_six_month_loan                         float64
history_suc_fee                               float64
history_fail_fee                              float64
latest_one_month_suc                          float64
latest_one_month_fail                         float64
loans_long_time                               float64
loans_credit_limit                            float64
loans_credibility_limit                       float64
loans_org_count_current                       float64
loans_product_count                           float64
loans_max_limit                               float64
loans_avg_limit                               float64
consfin_credit_limit                          float64
consfin_credibility                           float64
consfin_org_count_current                     float64
consfin_product_count                         float64
consfin_max_limit                             float64
consfin_avg_limit                             float64
latest_query_day                              float64
loans_latest_day                              float64
dtype: object

In [119]:
print(data["reg_preference_for_trad"].unique())

['一线城市' '三线城市' '境外' '二线城市' '其他城市' nan]

In [120]:
reg_preference_for_trad = {"一线城市":1,"二线城市":2,"三线城市":3,"境外":4,"其他城市":5}
#采用列表生成式对特征进行转换
#data["reg_preference_for_trad"] = [reg_preference_for_trad[x] for x in data["reg_preference_for_trad"] if x!= np.nan]
for i in range(0,data.shape[0]):
    if data["reg_preference_for_trad"][i] == "一线城市":
        data["reg_preference_for_trad"][i] = reg_preference_for_trad[data["reg_preference_for_trad"][i]]
    elif data["reg_preference_for_trad"][i] == "二线城市":
        data["reg_preference_for_trad"][i] = reg_preference_for_trad[data["reg_preference_for_trad"][i]]
    elif data["reg_preference_for_trad"][i] == "三线城市":
        data["reg_preference_for_trad"][i] = reg_preference_for_trad[data["reg_preference_for_trad"][i]]
    elif data["reg_preference_for_trad"][i] == "境外":
        data["reg_preference_for_trad"][i] = reg_preference_for_trad[data["reg_preference_for_trad"][i]]
    elif data["reg_preference_for_trad"][i] == "其他城市":
        data["reg_preference_for_trad"][i] = reg_preference_for_trad[data["reg_preference_for_trad"][i]]

In [121]:
#for columns in data.columns:
#   data[columns] = pd.to_numeric(data[columns])
data = data.convert_objects(convert_numeric = True)
data.dtypes

low_volume_percent                            float64
middle_volume_percent                         float64
take_amount_in_later_12_month_highest         float64
trans_amount_increase_rate_lately             float64
trans_activity_month                          float64
trans_activity_day                            float64
transd_mcc                                    float64
trans_days_interval_filter                    float64
trans_days_interval                           float64
regional_mobility                             float64
student_feature                               float64
repayment_capability                          float64
is_high_user                                  float64
number_of_trans_from_2011                     float64
first_transaction_time                        float64
historical_trans_amount                       float64
historical_trans_day                          float64
rank_trad_1_month                             float64
trans_amount_3_month                          float64
avg_consume_less_12_valid_month               float64
abs                                           float64
top_trans_count_last_1_month                  float64
avg_price_last_12_month                       float64
avg_price_top_last_12_valid_month             float64
reg_preference_for_trad                       float64
trans_top_time_last_1_month                   float64
trans_top_time_last_6_month                   float64
consume_top_time_last_1_month                 float64
consume_top_time_last_6_month                 float64
cross_consume_count_last_1_month              float64
trans_fail_top_count_enum_last_1_month        float64
trans_fail_top_count_enum_last_6_month        float64
trans_fail_top_count_enum_last_12_month       float64
consume_mini_time_last_1_month                float64
max_cumulative_consume_later_1_month          float64
max_consume_count_later_6_month               float64
railway_consume_count_last_12_month           float64
pawns_auctions_trusts_consume_last_1_month    float64
pawns_auctions_trusts_consume_last_6_month    float64
jewelry_consume_count_last_6_month            float64
status                                        float64
first_transaction_day                         float64
trans_day_last_12_month                       float64
apply_score                                   float64
apply_credibility                             float64
query_org_count                               float64
query_finance_count                           float64
query_cash_count                              float64
query_sum_count                               float64
latest_one_month_apply                        float64
latest_three_month_apply                      float64
latest_six_month_apply                        float64
loans_score                                   float64
loans_credibility_behavior                    float64
loans_count                                   float64
loans_settle_count                            float64
loans_overdue_count                           float64
loans_org_count_behavior                      float64
consfin_org_count_behavior                    float64
loans_cash_count                              float64
latest_one_month_loan                         float64
latest_three_month_loan                       float64
latest_six_month_loan                         float64
history_suc_fee                               float64
history_fail_fee                              float64
latest_one_month_suc                          float64
latest_one_month_fail                         float64
loans_long_time                               float64
loans_credit_limit                            float64
loans_credibility_limit                       float64
loans_org_count_current                       float64
loans_product_count                           float64
loans_max_limit                               float64
loans_avg_limit                               float64
consfin_credit_limit                          float64
consfin_credibility                           float64
consfin_org_count_current                     float64
consfin_product_count                         float64
consfin_max_limit                             float64
consfin_avg_limit                             float64
latest_query_day                              float64
loans_latest_day                              float64
dtype: object

In [124]:
pd.options.display.max_rows = 10
data["reg_preference_for_trad"]

0       1.0
1       1.0
2       1.0
3       3.0
4       1.0
       ...
4749    1.0
4750    1.0
4751    1.0
4752    1.0
4753    1.0
Name: reg_preference_for_trad, Length: 4754, dtype: float64

In [127]:
data = data.dropna(axis = 1,thresh = 1000)
data = data.dropna(axis = 0,thresh = 75)
data.shape

(4423, 82)

In [130]:
data = data.fillna(data.mean())
data

,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,transd_mcc,trans_days_interval_filter,trans_days_interval,regional_mobility,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,0.01,0.99,0.0,0.90,0.55,0.313,17.0,27.0,26.0,3.0,...,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,0.02,0.94,2000.0,1.28,1.00,0.458,19.0,30.0,14.0,4.0,...,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,0.04,0.96,0.0,1.00,1.00,0.114,13.0,68.0,22.0,1.0,...,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,0.00,0.96,2000.0,0.13,0.57,0.777,22.0,14.0,6.0,3.0,...,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,0.01,0.99,0.0,0.46,1.00,0.175,13.0,66.0,42.0,1.0,...,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4749,0.05,0.68,1000.0,0.87,0.94,0.150,16.0,32.0,24.0,4.0,...,0.0,0.0,49200.0,78.0,1.0,1.0,49200.0,49200.0,44.0,58.0
4750,0.01,0.99,400.0,0.93,0.98,0.605,18.0,18.0,16.0,3.0,...,5000.0,1952.0,10100.0,78.0,7.0,8.0,19200.0,7500.0,17.0,55.0
4751,0.00,1.00,3000.0,0.54,0.64,0.313,16.0,29.0,25.0,3.0,...,3300.0,1540.0,7600.0,79.0,8.0,8.0,21000.0,7250.0,18.0,55.0
4752,0.05,0.95,0.0,4.79,1.00,0.458,19.0,27.0,16.0,4.0,...,1900.0,1216.0,7100.0,79.0,8.0,11.0,12000.0,3950.0,55.0,16.0
4753,0.01,0.99,1300.0,21.35,1.00,0.372,22.0,22.0,21.0,2.0,...,4000.0,2180.0,4500.0,74.0,5.0,5.0,7800.0,4360.0,20.0,54.0

In [134]:
train_data,test_data = train_test_split(data,test_size = 0.3,random_state = 2018)
train_data.to_csv(r"C:\Users\hu\Desktop\datasets\train_data.csv",index = False,header = True)
test_data.to_csv(r"C:\Users\hu\Desktop\datasets\test_data.csv",index = False,header = True)